-- Fermina Food — cartel QR: añade platos de carta (rejilla) además del resumen UE
-- Ejecutar si el cartel muestra "no ha declarado alérgenos" pero sí hay gluten/leche en checklist.
-- Login: admin@fermina-food.local · QR: /alergenos/ferminafoodqr2026

UPDATE dakinis_core_prod.tenant_restaurant_profile
SET
  allergies_json = '[{"catalogId":"gluten","name":"Gluten","category":"Cereales","present":true,"severity":"alta","notes":"Pan choripán, rebozados"},{"catalogId":"crustaceans","name":"Crustáceos","category":"Marisco","present":false,"severity":"info","notes":""},{"catalogId":"eggs","name":"Huevos","category":"Huevo","present":false,"severity":"info","notes":""},{"catalogId":"fish","name":"Pescado","category":"Pescado","present":false,"severity":"info","notes":""},{"catalogId":"peanuts","name":"Cacahuetes","category":"Frutos secos","present":false,"severity":"info","notes":""},{"catalogId":"soy","name":"Soja","category":"Soja","present":false,"severity":"info","notes":""},{"catalogId":"milk","name":"Leche","category":"Lácteos","present":true,"severity":"alta","notes":"Bites cheddar"},{"catalogId":"nuts","name":"Frutos de cáscara","category":"Frutos secos","present":false,"severity":"info","notes":""},{"catalogId":"celery","name":"Apio","category":"Verdura","present":false,"severity":"info","notes":""},{"catalogId":"mustard","name":"Mostaza","category":"Condimento","present":false,"severity":"info","notes":""},{"catalogId":"sesame","name":"Sésamo","category":"Semillas","present":false,"severity":"info","notes":""},{"catalogId":"sulphites","name":"Sulfitos","category":"Conservantes","present":false,"severity":"info","notes":""},{"catalogId":"lupin","name":"Altramuz","category":"Legumbre","present":false,"severity":"info","notes":""},{"catalogId":"molluscs","name":"Moluscos","category":"Marisco","present":false,"severity":"info","notes":""},{"catalogId":"lactose","name":"Lactosa","category":"Intolerancia","present":false,"severity":"info","notes":""},{"catalogId":"vegan","name":"Vegano / vegetariano","category":"Preferencia","present":false,"severity":"info","notes":""},{"id":"dish_cheddar_jalapeno_bites","name":"Bites cheddar y jalapeños","category":"Entrante","present":true,"severity":"alta","notes":"Leche, Gluten"},{"id":"dish_chicken_bites","name":"Chicken bites","category":"Entrante","present":true,"severity":"alta","notes":"Gluten"},{"id":"dish_choripan","name":"Choripán","category":"Entrante","present":true,"severity":"alta","notes":"Gluten"}]',
  updated_at = now()
WHERE business_id = 'biz_fermina_food';
